/** Generated by scripts/inline-fonts-plugin.ts (registered in vite + vitest configs). */
declare module 'virtual:quiet-luxe-inline-fonts' {
  const inlineFontCss: string;
  export default inlineFontCss;
}
